ktor:
  application:
    modules:
      - org.abondar.experimental.urlshortner.ApplicationKt.module
  deployment:
    port: 8080

  redis:
    url: "redisL://localhost:6379"
    db: 0
    password: ""