ktor:
  application:
    modules:
      - org.abondar.experimental.urlshortner.ApplicationKt.module
  deployment:
    port: 8080

  redis:
    url: $REDIS_URL
    db: $REDIS_DB
    password: $REDIS_PASS